export const CHANGE_RECOMMEND_BANNERS = 'CHANGE_RECOMMEND_BANNERS';
export const CHANGE_HOT_RECOMMEND = 'CHANGE_HOT_RECOMMEND';
export const CHANGE_NEW_ALBUMS = 'CHANGE_NEW_ALBUMS';
export const CHANGE_SURGE_RANKING = 'CHANGE_SURGE_RANKING';
export const CHANGE_NEW_RANKING = 'CHANGE_NEW_RANKING';
export const CHANGE_ORIGIN_RANKING = 'CHANGE_ORIGIN_RANKING';
export const CHANGE_SETTLE_SINGERS = 'CHANGE_SETTLE_SINGERS';
